---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - landscaper.services.openmcp.cloud
  resources:
  - landscapers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - landscaper.services.openmcp.cloud
  resources:
  - landscapers/finalizers
  verbs:
  - update
- apiGroups:
  - landscaper.services.openmcp.cloud
  resources:
  - landscapers/status
  verbs:
  - get
  - patch
  - update
