name: CI

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version-file: go.mod

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: task generate
        run: |
          task generate --verbose
          git diff --exit-code

      - name: task validate
        run: task validate --verbose

      - name: task test
        run: task test --verbose

  validate-pr-content:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Validate PR content
        run: |
          PR_BODY=$(jq -r .pull_request.body "$GITHUB_EVENT_PATH")
          echo "DEBUG: PR_BODY content is: $PR_BODY"
          REQUIRED_SECTIONS=("\\*\\*What this PR does / why we need it\\*\\*:" "\\*\\*Release note\\*\\*:")

          for SECTION in "${REQUIRED_SECTIONS[@]}"; do
            echo "DEBUG: Checking for section: $SECTION"
            if ! echo "$PR_BODY" | grep -qE "$SECTION"; then
              echo "Pull request message is missing required section: $SECTION" >&2
              exit 1
            fi
          done
